import { LineEdit, VerticalBox, Button, ProgressIndicator, TabWidget, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <bool> credentialcreation: true;
    property <bool> credentialsfilled: false;
    property <bool> showcompletedload: false;
    property <int> loadingbarcompletion: 0;
    in property <int> tabnumber;
    in-out property <bool> refreshbutton: false;
    property <length> infofontsize: root.height * 0.035;
    in-out property <string> dockeroutput1;
    in-out property <string> dockeroutput2;
    in-out property <string> dockeroutput3;
    in-out property <string> dockeroutput4;
    in-out property <string> dockeroutput5;
    in-out property <string> dockeroutput6;
    in-out property <string> dockeroutput7;
    in-out property <string> dockeroutput8;
    in-out property <string> dockeroutput9;
    in-out property <string> dockeroutput10;
    preferred-width: 800px;
    preferred-height: 600px;
    min-width: 600px;
    min-height: 600px;

    callback send_credentials(string, string, string);
    callback send_refresh_state(bool);

    title: "Docker UI";
    default-font-family: "JetBrains Mono";
    resize-border-width: 0px;

    VerticalBox {
        uiusername:= LineEdit {
            visible: root.credentialcreation;
            max-height: 40px;
            placeholder-text: "Username";
            horizontal-alignment: center;
        }
        uipassword:= LineEdit {
            visible: root.credentialcreation;
            max-height: 40px;
            placeholder-text: "Password";
            input-type: password;
            horizontal-alignment: center;
        }
        uiipaddress:= LineEdit {
            visible: root.credentialcreation;
            max-height: 40px;
            placeholder-text: "IP Address";
            horizontal-alignment: center;
            accepted(text) => {
                root.credentialsfilled = true;
            }
        }
        if root.credentialcreation && root.credentialsfilled: Button {
            text: "Submit";
            preferred-height: 40px;
            preferred-width: 100px;
            
            clicked => {
                root.credentialcreation = false;
                send_credentials(uiusername.text, uipassword.text, uiipaddress.text);
            }
        }
        Button {
            text: "Refresh";
            clicked => {
                root.refreshbutton = true;
                send_refresh_state(true)
            }
        }
        TabWidget {
            preferred-height: 200px;
            Tab {
                title: "Containers";
                HorizontalBox {
                    rect1:= Rectangle {
                        border-radius: 10px;
                        border-color: #0400ff;
                        border-width: 1px;
                        height: text1.height + 30px;
                        width: text1.width + 30px;
                        text1:= Text {
                            text: dockeroutput1;
                            font-size: 25pt;
                            letter-spacing: 4px;
                        }
                    }
                    Rectangle {
                        border-radius: 10px;
                        border-color: #0400ff;
                        border-width: 1px;
                        height: text2.height + 30px;
                        width: text2.width + 30px;
                        text2:= Text {
                            text: dockeroutput2;
                        }
                    }
                    Rectangle {
                        border-radius: 10px;
                        border-color: #0400ff;
                        border-width: 1px;
                        height: text3.height + 30px;
                        width: text3.width + 30px;
                        text3:= Text {
                            text: dockeroutput3;
                        }
                    }
                }
            }
            Tab {
                title: "Images";
                HorizontalBox {
                    Rectangle {
                        border-radius: 10px;
                        border-color: #0400ff;
                        border-width: 1px;
                        height: text4.height + 30px;
                        width: text4.width + 30px;
                        text4:= Text {
                            text: dockeroutput4;
                        }
                    }
                    Rectangle {
                        border-radius: 10px;
                        border-color: #0400ff;
                        border-width: 1px;
                        height: text5.height + 30px;
                        width: text5.width + 30px;
                        text5:= Text {
                            text: dockeroutput5;
                        }
                    }
                    Rectangle {
                        border-radius: 10px;
                        border-color: #0400ff;
                        border-width: 1px;
                        height: text6.height + 30px;
                        width: text6.width + 30px;
                        text6:= Text {
                            text: dockeroutput6;
                        }
                    }
                    Rectangle {
                        border-radius: 10px;
                        border-color: #0400ff;
                        border-width: 1px;
                        height: text7.height + 30px;
                        width: text7.width + 30px;
                        text7:= Text {
                            text: dockeroutput7;
                        }
                    }
                }
            }
            Tab {
                title: "System";
                Rectangle {
                    border-radius: 10px;
                    border-color: #0400ff;
                    border-width: 1px;
                    height: text8.height + 30px;
                    width: text8.width + 30px;
                    text8:= Text {
                        text: dockeroutput8;
                    }
                }
            }
        }
    }
}
