import { LineEdit, VerticalBox, Button, ProgressIndicator, TabWidget, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <bool> credentialcreation: true;
    property <bool> credentialsfilled: false;
    property <bool> showcompletedload: false;
    property <int> loadingbarcompletion: 0;
    in property <int> tabnumber;
    in-out property <bool> refreshbutton: false;
    in-out property <string> dockeroutput1;
    in-out property <string> dockeroutput2;
    in-out property <string> dockeroutput3;
    in-out property <string> dockeroutput4;
    in-out property <string> dockeroutput5;
    in-out property <string> dockeroutput6;
    in-out property <string> dockeroutput7;
    in-out property <string> dockeroutput8;
    in-out property <string> dockeroutput9;
    in-out property <string> dockeroutput10;
    preferred-width: 800px;
    preferred-height: 600px;
    min-width: 600px;
    min-height: 600px;

    callback send_credentials(string, string, string);
    callback send_refresh_state(bool);

    title: "Docker UI";
    default-font-family: "JetBrains Mono";
    resize-border-width: 0px;

    VerticalBox {
        uiusername:= LineEdit {
            visible: root.credentialcreation;
            max-height: 40px;
            placeholder-text: "Username";
            horizontal-alignment: center;
        }
        uipassword:= LineEdit {
            visible: root.credentialcreation;
            max-height: 40px;
            placeholder-text: "Password";
            input-type: password;
            horizontal-alignment: center;
            text: "";
        }
        uiipaddress:= LineEdit {
            visible: root.credentialcreation;
            max-height: 40px;
            placeholder-text: "IP Address";
            horizontal-alignment: center;
            accepted(text) => {
                root.credentialsfilled = true;
            }
        }
        if root.credentialcreation && root.credentialsfilled: Button {
            text: "Submit";
            preferred-height: 40px;
            preferred-width: 100px;
            
            clicked => {
                root.credentialcreation = false;
                send_credentials(uiusername.text, uipassword.text, uiipaddress.text);
            }
        }
        Button {
            text: "Refresh";
            clicked => {
                root.refreshbutton = true;
                send_refresh_state(true)
            }
        }
        TabWidget {
            preferred-height: 200px;
            Tab {
                
                title: "Containers";
                HorizontalBox {
                    Rectangle {
                        border-radius: 10px;
                        border-color: red;
                        border-width: 3px;
                        Text {
                            text: dockeroutput1;
                        }
                    }
                    Rectangle {
                        border-radius: 10px;
                        border-color: aquamarine;
                        border-width: 3px;
                        Text {
                            text: dockeroutput3;
                        }
                    }
                    Rectangle {
                        border-radius: 10px;
                        border-color: cyan;
                        border-width: 3px;
                        Text {
                            text: dockeroutput2;
                        }
                    }
                }
            }
            Tab {
                title: "Images";
                HorizontalBox {
                    Text {
                        text: dockeroutput4;
                    }
                    Text {
                        text: dockeroutput5;
                    }
                    Text {
                        text: dockeroutput6;
                    }
                    Text {
                        text: dockeroutput7;
                    }
                }
            }
            Tab {
                title: "System";
                Text {
                    text: dockeroutput8;
                }
            }
        }
    }
}
